# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "ShouldIBikeApp" do
    pod 'SBJson', '~> 2.2.3'
	pod 'AFNetworking', '~> 2.0'
    pod 'UITintedButton'
end

target "ShouldIBikeAppTests" do

end

